### ISSUE TITLE
List of workers can give wrong result

### ISSUE THREAD

**Issue by jirihnidek** [RedHatInsights/yggdrasil#135]
**Describe the bug**
List of workers can be incomplete or it can contain workers that are not active anymore

**To Reproduce**
1. Start yggdrasil on Terminal 1: `go run ./cmd/yggd --server tcp://localhost:1883 --log-level trace --client-id $(hostname)`
2. Start echo worker on Terminal 2: `go run ./worker/echo -log-level trace`
3. Try to get list of workers on Terminal 3 using: `go run ./cmd/yggctl workers list` or `busctl --user call com.redhat.Yggdrasil1 /com/redhat/Yggdrasil1 com.redhat.Yggdrasil1 ListWorkers`

**Current result**
List of workers is empty. The worker gets into the list of workers only after receiving the first message from MQTT.

**Expected behavior**
List of running workers.

Something like this in the case of `yggctl`:
```
echo - DispatchedAt:
echo - Version: 1
```

Something like this in the case of `busctl` (or any other D-Bus app):
```
a{sa{ss}} 1 "echo" 2 "Version" "1" "DispatchedAt" ""
```

**Additional Information**
 - OS: Fedora 38
 - Version: main branch

When worker has been stopped, then you can still see worker in the list of active workers despite MQTT message for the worker has been received and yggdrasil wasn't able to dispatch data from the MQTT message.

**Comment by jirihnidek** [comment]
Started discussion that is related to this issue: https://github.com/RedHatInsights/yggdrasil/discussions/169

**Comment by subpop** [comment]
Each worker is expected to own a name on the bus under the namespace `com.redhat.Yggdrasil1.Worker1` (i.e. `com.redhat.Yggdrasil1.Worker1.echo`). When asked for a list of workers, `yggd` should enumerate all names on the bus, filter for names that begin with the namespace value above, and return the results.
