### ISSUE TITLE
yggd does not detect new workers automatically

### ISSUE THREAD

**Issue by subpop** [RedHatInsights/yggdrasil#153]
**Describe the bug**
When a worker starts up, yggd does not automatically discover the worker and update its table of known workers.

**To Reproduce**
1. Start an MQTT client subscribed to a client's topic set (specifically, control/out)
2. Start yggd
3. Start a worker

**Expected behavior**
When subscribed to a client's topics, an updated "connection-status" message should be published, containing the newly started worker in the "dispatchers" field.

**Comment by jirihnidek** [comment]
This is duplicated issue of this issue https://github.com/RedHatInsights/yggdrasil/issues/135. I propose to close this issue and keep only original issue.
