### ISSUE TITLE
RPC error - wrong number of arguments

### ISSUE THREAD

**Issue by ezr-ondrej** [RedHatInsights/yggdrasil#30]
yggdrasil version: 0.1.4

```
dispatcher.go:309: rpc error: code = Unknown desc = ArgumentError: wrong number of argumets (given 2, expected 1)
```

I believe the error is here: https://github.com/RedHatInsights/yggdrasil/blob/d68f8c2a85b8d251a00213e2e9fc1a672f8d7aca/dispatcher.go#L293

Here is the simple client I'm using: https://github.com/ezr-ondrej/foreman_ygg_worker

The gRPC proto has been generated from protocol in this repository, so eighter the `proto` is wrong or the bug is in the code?

**Comment by subpop** [comment]
Could you set `log-level = trace` in `/etc/yggdrasil/config.toml` (or `/etc/rhc/config.toml`, if you're using the `rhc` RPM), and attach the output?

**Comment by ezr-ondrej** [comment]
Hi, sorry it took a bit of time, here is a relevant snippet:
```
Apr 30 06:03:19 yggclien.oezr-fedora.example.com yggdrasild[11085]: [yggdrasild] [*yggdrasil.DataProcessor] 2021/04/30 06:03:19 /builddir/build/BUILD/yggdrasil-0.1.4-0.7.git.9789afc/data_processor.go:156: HandleDataRecvSignal
Apr 30 06:03:19 yggclien.oezr-fedora.example.com yggdrasild[11085]: [yggdrasild] [*yggdrasil.DataProcessor] 2021/04/30 06:03:19 /builddir/build/BUILD/yggdrasil-0.1.4-0.7.git.9789afc/data_processor.go:156: received value: "41a3d36f-c590-4c07-8e95-11fb4b8f8505"
Apr 30 06:03:19 yggclien.oezr-fedora.example.com yggdrasild[11085]: [yggdrasild] [*yggdrasil.DataProcessor] 2021/04/30 06:03:19 /builddir/build/BUILD/yggdrasil-0.1.4-0.7.git.9789afc/data_processor.go:156: emitted signal "data-process"
Apr 30 06:03:19 yggclien.oezr-fedora.example.com yggdrasild[11085]: [yggdrasild] [*yggdrasil.DataProcessor] 2021/04/30 06:03:19 /builddir/build/BUILD/yggdrasil-0.1.4-0.7.git.9789afc/data_processor.go:156: emitted value: "41a3d36f-c590-4c07-8e95-11fb4b8f8505"
Apr 30 06:03:19 yggclien.oezr-fedora.example.com yggdrasild[11085]: [yggdrasild] [*yggdrasil.Dispatcher] 2021/04/30 06:03:19 /builddir/build/BUILD/yggdrasil-0.1.4-0.7.git.9789afc/dispatcher.go:309: HandleDataProcessSignal
Apr 30 06:03:19 yggclien.oezr-fedora.example.com yggdrasild[11085]: [yggdrasild] [*yggdrasil.Dispatcher] 2021/04/30 06:03:19 /builddir/build/BUILD/yggdrasil-0.1.4-0.7.git.9789afc/dispatcher.go:309: emitted value: "41a3d36f-c590-4c07-8e95-11fb4b8f8505"
Apr 30 06:03:19 yggclien.oezr-fedora.example.com yggdrasild[11085]: [yggdrasild] [*yggdrasil.Dispatcher] 2021/04/30 06:03:19 /builddir/build/BUILD/yggdrasil-0.1.4-0.7.git.9789afc/dispatcher.go:309: dialing worker foreman
Apr 30 06:03:19 yggclien.oezr-fedora.example.com yggdrasild[11085]: [yggdrasild] [*yggdrasil.Dispatcher] 2021/04/30 06:03:19 /builddir/build/BUILD/yggdrasil-0.1.4-0.7.git.9789afc/dispatcher.go:309: rpc error: code = Unknown desc = ArgumentError: wrong number of arguments (given 2, expected 1)
```

Full log: https://pastebin.com/0sASLXv0

**Comment by ezr-ondrej** [comment]
My bad, this was caused by missing `call` param, that's passed by gRPC. Fixed in https://github.com/ezr-ondrej/foreman_ygg_worker/commit/0150e1a480e1a57b9e7cc80d4f9efee4588aca45

**Comment by subpop** [comment]
Oh wow. That looks to be an idiosyncrasy of the Ruby gRPC package, perhaps? Is `_call` a callback handler function? I can't see it defined anywhere in `foreman_worker`.

**Comment by ezr-ondrej** [comment]
well... it is abuse of ruby's dynamic programing IMHO. You don't define the Service classes that will be actually used, but you define classes, that will generate the classes, you end up using. It is very confusing.

From what I understood in documentation, it is used for streaming. I guess you can get other information about the message from the `_call`.
