### ISSUE TITLE
Support systemd notify protocol

### ISSUE THREAD

**Issue by ekohl** [RedHatInsights/yggdrasil#56]
The current systemd service uses `type=simple`. This means systemd knows very little about the internal state. Using [sd_notify](https://www.freedesktop.org/software/systemd/man/sd_notify.html#Description) a daemon can tell systemd a lot more which makes the life of sysadmins easier. For example, it can only mark the service as running when it has parsed all configs or any other initialization.

A quick look shows CoreOS has implemented this in [go-systemd](https://github.com/coreos/go-systemd). They also have code to support systemd's watchdog.

**Comment by subpop** [comment]
Fixed in 9be934522d9dbda4ce507c4f0162de5b021f33a3
