### ISSUE TITLE
Add support for retries when performing HTTP requests

### ISSUE THREAD

**Issue by adamruzicka** [RedHatInsights/yggdrasil#98]
**Describe the bug**
Currently, when Yggdrasil performs a HTTP request which fails (in my case a timeout during tls negotiation, but any kind of error should be generally applicable) it just gives up. It would be nice if yggdrasil could wait for a bit and try again a couple of times

It is not necessarily a bug, but it would be a nice improvement.

**Comment by adamruzicka** [comment]
It might be also helpful making yggdrasil honor http headers such as Retry-After to allow http servers to moderate the traffic before they tip over under the load

**Comment by subpop** [comment]
Fixed in https://github.com/RedHatInsights/yggdrasil/commit/aac0301b0ceea10ac77207250070cf513d40d22b
